# Use the official NGINX image as the base
FROM nginx:1.27.3-alpine

# Copy your NGINX template configuration to the appropriate directory
COPY ./config/nginx/dev.conf.template /etc/nginx/templates/default.conf.template

# Expose ports
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
