version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install cfn-lint
  
  build:
    commands:
      - echo "Validating CloudFormation template..."
      - cfn-lint infra.yaml
      - aws cloudformation validate-template --template-body file://infra.yaml
      - echo "Template validation complete on $(date)"

  post_build:
    commands:
      - echo "Listing files to be included in artifacts..."
      - ls -la
      - echo "Copying files to artifact directory..."
      - cp infra.yaml ${CODEBUILD_SRC_DIR}/
      - cp params.json ${CODEBUILD_SRC_DIR}/ || echo "params.json not found"

artifacts:
  files:
    - infra.yaml
    - params.json
    - '**/*'
  discard-paths: no
