version: 0.2

phases:
  build:
    commands:
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --template-body file://ecs-cluster.yaml

artifacts:
  files:
    - ecs-cluster.yaml
    - params.json
  discard-paths: no
