version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install cfn-lint
  
  build:
    commands:
      - echo "Validating CloudFormation template..."
      - cfn-lint infra.yaml
      - aws cloudformation validate-template --template-body file://infra.yaml
      - echo "Template validation complete on $(date)"

artifacts:
  files:
    - infra.yaml
    - params.json
    - '**/*'
  discard-paths: no
