name: Bootstrap CI/CD Pipeline

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install cfn-lint
        run: |
          pip install cfn-lint

      - name: Lint CloudFormation template
        run: |
          cfn-lint cicd.yml

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name ecs-demo-cicd \
            --template-file cicd.yml \
            --parameter-overrides file://params.json \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
            --no-fail-on-empty-changeset
      
      - name: Verify Stack deployment
        if: github.ref == 'refs/heads/cicd' && github.event_name == 'push'
        run: |
          aws cloudformation describe-stacks \
            --stack-name ecs-demo-cicd \
            --query 'Stacks[0].StackStatus' \
            --output text

